[package]
name = "bot-helper"
version = "0.1.0"
edition = "2024"

[target.'cfg(not(windows))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[dependencies]
anyhow = "1.0.100"
daily-greeting = { version = "0.1.0", path = "plugins/daily-greeting" }
deploy = { version = "0.1.0", path = "plugins/deploy" }
feedback = { version = "0.1.0", path = "plugins/feedback" }
kovi = "0.12.7"
kovi-plugin-cmd = "0.3.0"

[workspace]
members = ["plugins/feedback", "plugins/daily-greeting", "plugins/deploy"]

[workspace.dependencies]
kovi = "0.12.7"
