[feedback]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[feedback.access_list]
friends = []
groups = []

[kovi-plugin-cmd]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[kovi-plugin-cmd.access_list]
friends = []
groups = []

[deploy]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[deploy.access_list]
friends = []
groups = []

[daily_greeting]
enable_on_startup = true
access_control = false
list_mode = "WhiteList"

[daily_greeting.access_list]
friends = []
groups = []
